name: artifacts
on: push
jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/notcustom.txt
      
    - run: echo world > path/to/artifact/custom.txt

    - uses: actions/upload-artifact@master
      with:
        name: artifact
        path: path/to/artifact/notcustom.txt
        
    - uses: actions/upload-artifact@master
      with:
        name: custom retention artifact
        path: path/to/artifact/custom.txt
        retention-days: 1
